# Generated by Django 3.2.8 on 2021-10-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('phone', models.PositiveBigIntegerField()),
                ('profilepic', models.ImageField(upload_to='profileimages')),
                ('emailid', models.EmailField(max_length=254)),
                ('quailification', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('idname', models.CharField(max_length=20)),
                ('banner_image', models.ImageField(upload_to='bannerImages')),
                ('timeofjoin', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
